### PR TITLE
added templates

### PR DESCRIPTION
**Pull request by danielepolencic**

### CODE REVIEW

**Comment by timgent** [comment]
LGTM - at some point we should ask if they can use other formats, but given .docx is what everyone always requests I think it is ok to leave it as this for now

**Comment by chrisns** [comment]
we could use markdown and give a link to https://cloudconvert.com/md-to-docx ? ;)

**Comment by danielepolencic** [comment]
Does it work with embedded images?

**Comment by chrisns** [comment]
@danielepolencic example: https://host123d1qv.cloudconvert.com/download/~yJIn-yW_bS04XL9QrII1yiI6ons

**Comment by chrisns** [comment]
@danielepolencic based on: https://github.com/UKHomeOffice/removals_e2etests/blob/master/README.md

**Comment by chrisns** [comment]
so yes, you can put memes in the job specs...

**Pull request merged**
